openapi: 3.0.0
info:
  title: docai-api
  version: 1.0.0

servers:
  - url: https://docai-api.endpoints.molawcounter.cloud.goog

paths:
  /docAI:
    post:
      operationId: docAI
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                base64:
                  type: string
      responses:
        '200':
          description: Document AI result

x-google-backend:
  address: https://docai-server-989958208701.us-central1.run.app
  protocol: h2

x-google-endpoints:
  - name: docai-api.endpoints.molawcounter.cloud.goog
    allowCors: true
