swagger: "2.0"
info:
  title: "docai-api"
  description: "Document AI Gateway"
  version: "1.0.0"

host: "docai-api.endpoints.molawcounter.cloud.goog"
schemes:
  - https

paths:
  /docAI:
    post:
      summary: "Document AI processing"
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              base64:
                type: string
      responses:
        200:
          description: "Document AI result"

x-google-endpoints:
  - name: docai-api.endpoints.molawcounter.cloud.goog
    allowCors: true

x-google-backend:
  address: https://docai-server-989958208701.us-central1.run.app
  protocol: h2
